[package]
name = "neural"
version = "0.1.0"
authors = ["Andrew Fluth <afluth@gmail.com>"]

[dependencies]
rand = "0.3"
scoped_threadpool = "0.1"
num_cpus = "0.2"
rustc-serialize = "0.3"
clap = "2.2"
log = "0.3"